env_type: dreamdojo_wm
task_suite_name: g1_pick_trocar
wm_env_type: g1_dex3

total_num_envs: null
auto_reset: false
ignore_terminations: false
max_steps_per_rollout_epoch: 250
max_episode_steps: 250
use_rel_reward: false

seed: 0
group_size: 1
use_fixed_reset_state_ids: true
is_eval: false

video_cfg:
  save_video: true
  info_on_video: true
  video_base_dir: ${runner.logger.log_path}/video/train

enable_offload: false

dreamdojo_path: "/localhome/local-yunl/DreamDojo"
config_file: "cosmos_predict2/_src/predict2/action/configs/action_conditioned/config.py"
experiment_name: "dreamdojo_2b_480_640_g1_pick_trocar_headcam"
model_path: "/localhome/local-yunl/DreamDojo/outputs/train/dreamdojo/pick_trocar_headcam/g1_pick_trocar_headcam_2b/checkpoints/iter_000010000/model_ema_bf16.pt"
initial_dataset_path: "/localhome/local-yunl/DreamDojo/datasets/g1_pick_trocar_200_headcam"
action_statistics_path: "/localhome/local-yunl/DreamDojo/shared_meta/G1_stats.json"
task_description: "Pick up the trocar with the right hand."

context_parallel_size: 1
num_inference_steps: 35
guidance: 0
chunk: 25
image_size: [480, 640]

reward_model:
  checkpoint_path: "/localhome/local-yunl/RLinf/success_classifier/dreamdojo_progress_run/checkpoints/best.pt"
  hidden_dim: 256
  dropout: 0.1
  temporal_window: 8
  success_threshold: 0.8
  majority_fraction: 0.75
  min_stable_frames: 4
